import { SectionHeading } from "@/components/section-heading";
import { readTerminalData } from "@/lib/pumpData";
import { formatPercent, formatSol, formatUsd, relativeTime, shortAddress } from "@/lib/pumpPresentation";

export const dynamic = "force-dynamic";
export const metadata = { title: "Treasury | PumpXBT" };

export default async function TreasuryPage() {
  const data = await readTerminalData();
  const realizedUsd = data.treasuryEvents.filter((event) => event.event_type === "trade_profit").reduce((sum, event) => sum + (event.amount_usd ?? 0), 0);
  const burns = data.treasuryEvents.filter((event) => event.event_type === "burn");
  const buybacks = data.treasuryEvents.filter((event) => event.event_type === "buyback");
  return <main className="route-page page-width"><div className="route-intro"><SectionHeading eyebrow="PUMPXBT / TREASURY" title="THE PUMPXBT FLYWHEEL" description="Verifiable positions, realized outcomes, buybacks, and burns." /><div className="route-status"><span><i className={data.connected ? "live" : ""} />LEDGER ONLINE</span><strong>{data.autoTrades.length} POSITIONS</strong><strong>{buybacks.length} BUYBACKS</strong><strong>{burns.length} BURNS</strong></div></div><div className="flywheel treasury-flywheel"><strong>FEES</strong><span>→</span><strong>PLAYS</strong><span>→</span><strong>PROFITS</strong><span>→</span><strong>BUYBACK & BURN</strong></div><div className="profile-stats treasury-stats"><article><span>REALIZED PROFIT</span><strong>{realizedUsd ? formatUsd(realizedUsd) : "--"}</strong></article><article><span>RECORDED BUYBACKS</span><strong>{buybacks.length}</strong></article><article><span>RECORDED BURNS</span><strong>{burns.length}</strong></article><article><span>OPEN LEDGER ROWS</span><strong>{data.autoTrades.length}</strong></article></div><section className="route-panel"><header><span>POSITION LEDGER</span><small>PUBLIC EXECUTION RECORDS</small></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Token</th><th>Status</th><th>Entry</th><th>Current</th><th>PnL</th><th>Time</th><th>Proof</th></tr></thead><tbody>{data.autoTrades.map((trade) => <tr key={trade.id}><td><strong>{trade.token_symbol || trade.token?.symbol || shortAddress(trade.token_mint)}</strong></td><td>{trade.status.toUpperCase()}</td><td>{formatSol(trade.sol_amount)}</td><td>{formatSol(trade.current_sol_value)}</td><td className={(trade.pnl_percent ?? 0) >= 0 ? "positive" : "negative"}>{formatPercent(trade.pnl_percent)}</td><td>{relativeTime(trade.created_at)} ago</td><td>{trade.tx_signature ? <a href={`https://solscan.io/tx/${trade.tx_signature}`} target="_blank" rel="noreferrer">TX ↗</a> : "--"}</td></tr>)}{data.autoTrades.length === 0 ? <tr><td colSpan={7} className="table-empty">LEDGER QUIET — No verified execution has cleared yet.</td></tr> : null}</tbody></table></div></section><section className="route-panel"><header><span>TREASURY EVENTS</span><small>CONFIRMED SIGNATURES ONLY</small></header><div className="treasury-event-list">{data.treasuryEvents.map((event) => <a key={event.signature} href={`https://solscan.io/tx/${event.signature}`} target="_blank" rel="noreferrer"><i className={`treasury-icon ${event.event_type}`} /> <span><strong>{event.event_type.replaceAll("_", " ").toUpperCase()}</strong><small>{event.memo || shortAddress(event.signature)}</small></span><b>{event.amount.toLocaleString("en-US", { maximumFractionDigits: 4 })} {event.token}<small>{formatUsd(event.amount_usd)}</small></b><time>{relativeTime(event.block_time)} ago</time></a>)}{data.treasuryEvents.length === 0 ? <div className="product-empty">NO VERIFIED TREASURY EVENTS — Confirmed signatures appear here.</div> : null}</div></section></main>;
}
