import Link from "next/link";

import { SectionHeading } from "@/components/section-heading";
import { readTerminalData } from "@/lib/pumpData";
import { buildWalletClusters, formatUsd, relativeTime, shortAddress } from "@/lib/pumpPresentation";

export const dynamic = "force-dynamic";
export const metadata = { title: "Smart Money | PumpXBT" };

export default async function WalletsPage() {
  const data = await readTerminalData();
  const clusters = buildWalletClusters(data.walletEvents);
  const eventsByWallet = new Map<string, typeof data.walletEvents>();
  for (const event of data.walletEvents) eventsByWallet.set(event.wallet_address, [...(eventsByWallet.get(event.wallet_address) ?? []), event]);
  return <main className="route-page page-width"><div className="route-intro"><SectionHeading eyebrow="PUMPXBT / SMART MONEY" title="TRACK THE WALLETS THAT MATTER" description="Verified public wallet activity across indexed Pump.fun markets." /><div className="route-status"><span><i className={data.connected ? "live" : ""} />HELIUS FEED</span><strong>{data.wallets.length} WALLETS</strong><strong>{data.walletEvents.length} EVENTS</strong></div></div><section className="wallet-overview"><div className="route-panel"><header><span>ACTIVE CLUSTERS</span><small>BY DISTINCT WALLETS</small></header><div className="cluster-list">{clusters.map((cluster) => <Link key={cluster.tokenMint} href={`/terminal?q=${encodeURIComponent(cluster.tokenMint)}`}><div><i className="flow-dot" /><strong>{cluster.token}</strong><span>{cluster.walletCount} wallet{cluster.walletCount === 1 ? "" : "s"}</span></div><small>{cluster.buyCount} buys · {relativeTime(cluster.latest)} ago</small></Link>)}{clusters.length === 0 ? <div className="product-empty">No wallet clusters detected in the indexed event window.</div> : null}</div></div><div className="route-panel"><header><span>TRACKED WALLETS</span><small>OPERATOR-CURATED</small></header><div className="tracked-wallet-list">{data.wallets.map((wallet) => { const events = eventsByWallet.get(wallet.address) ?? []; const latest = events[0]; return <article key={wallet.address}><i>{wallet.label.slice(0, 2).toUpperCase()}</i><div><strong>{wallet.label}</strong><span>{shortAddress(wallet.address)} · {wallet.category.replaceAll("_", " ")}</span></div><small>{events.length} events<br />{latest ? `${relativeTime(latest.block_time)} ago` : "no activity"}</small></article>; })}{data.wallets.length === 0 ? <div className="product-empty">No tracked wallets configured.</div> : null}</div></div></section><section className="route-panel"><header><span>LIVE WALLET ACTIVITY</span><small>PUBLIC CHAIN EVENTS</small></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Wallet</th><th>Action</th><th>Token</th><th>Amount</th><th>USD</th><th>Time</th><th>Proof</th></tr></thead><tbody>{data.walletEvents.map((event) => <tr key={event.id}><td><strong>{event.wallet?.label || shortAddress(event.wallet_address)}</strong></td><td className={event.direction === "buy" ? "positive" : event.direction === "sell" ? "negative" : ""}>{event.direction.toUpperCase()}</td><td>{event.token?.symbol ? `$${event.token.symbol.toUpperCase()}` : shortAddress(event.token_mint)}</td><td>{event.token_amount?.toLocaleString("en-US", { maximumFractionDigits: 3 }) ?? "--"}</td><td>{formatUsd(event.amount_usd)}</td><td>{relativeTime(event.block_time)} ago</td><td><a href={`https://solscan.io/tx/${event.signature}`} target="_blank" rel="noreferrer">TX ↗</a></td></tr>)}{data.walletEvents.length === 0 ? <tr><td colSpan={7} className="table-empty">No verified wallet events in the current window.</td></tr> : null}</tbody></table></div></section></main>;
}
